Homework_1
Mariyka-soul/Education pull request #1
Opened 2024-02-12 09:14 UTC by Mariyka-soul

2024-02-12 12:33 UTC, Gribok4E requested changes

2024-02-12 12:33 UTC, Gribok4E commented on Homework/Homework_1/Homework_1/Program.cs
> +
Зачем здесь отступ?

2024-02-12 12:33 UTC, Gribok4E commented on Homework/Homework_1/Homework_1/Program.cs
> +
Зачем здесь отступ?

2024-02-12 12:33 UTC, Gribok4E commented on Homework/Homework_1/Homework_1/Program.cs
> +}
Нужно убрать кучу пустых строк

2024-02-13 20:36 UTC, vemontd1 approved these changes

2024-03-10 16:05 UTC, merged